mutex: mutex.c
	gcc -o mutex mutex.c

semaphore: semaphore.c
	gcc -o semaphore semaphore.c 

spinlock: spinlock.c
	gcc -o spinlock spinlock.c

share_memory_read:shared_memory_read.c
	gcc -o shared_memory_read shared_memory_read.c

share_memory_write:shared_memory_write.c
	gcc -o shared_memory_write shared_memory_write.c



